#
# Module manifest for module 'EXORBACforAppManagement'
#
# Generated by: Ziemek Borowski
#
# Generated on: 07.06.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'EXORBACforAppManagement.psm1'

# Version number of this module.
ModuleVersion = '0.4.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '8a06e703-e3a2-45a9-9504-c0cb6a78e355'

# Author of this module
Author = 'Ziemek Borowski'

# Company or vendor of this module
CompanyName = 'ziembor'

# Copyright statement for this module
Copyright = '(c) 2026 Ziemek Borowski. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Exchange Online RBAC governance for Entra application service principals: register apps, assign EXO application role scopes, and read them back. Requires the Microsoft.Graph and ExchangeOnlineManagement modules to be installed and connected at runtime (not declared as RequiredModules so the module imports without them for unit testing).'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'New-RBACforAppEntry', 'New-RegisteredApp', 'Get-RBACforAppEntry', 'Get-RegisteredAppWithPermission', 'New-RBACforAppUnifiedGroup', 'Register-EXOServicePrincipal', 'Convert-ApplicationAccessPolicyToRBAC', 'Test-RBACforAppEntry', 'Remove-RBACforAppEntry', 'Set-RBACforAppEntry'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Exchange', 'ExchangeOnline', 'RBAC', 'Entra', 'AzureAD', 'Graph', 'M365'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ziembor/new-RBACforAppEntry'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '0.4.1 - Renamed the module from RBACforAppGovern to EXORBACforAppManagement (module identity only; public function names and the manifest GUID are unchanged). New-RBACforAppEntry / New-RBACforAppUnifiedGroup now report the Unified Group owner as OwnerRequested/OwnerAdded. 0.4.0 - Added Convert-ApplicationAccessPolicyToRBAC: migrates legacy Application Access Policies to RBAC for Applications by deriving roles from the app''s Graph permission grants and delegating to New-RBACforAppEntry. 0.3.0 - Get-RBACforAppEntry now filters by assignee type, defaulting to ServicePrincipal (use -RoleAssigneeType All or a specific type to change). 0.2.1 - Default -ManagedBy is now GraphAPI-Dummy-owner (a group owner must be a valid owner account, distinct from a plain member). 0.2.0 - Extracted New-RBACforAppUnifiedGroup and Register-EXOServicePrincipal as public functions; New-RBACforAppEntry now delegates to them.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

